# Generated by Django 3.0.3 on 2020-02-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
